import streamlit as st
from streamlit_lottie import st_lottie
import requests

# Set the Streamlit page configuration
st.set_page_config(page_title="Quiz Customizer", page_icon="📚", layout="centered")

# Function to load Lottie animation
def load_lottie_url(url: str):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

# Function to call the Gemini API to generate quizzes
def generate_quiz_gemini(quiz_data):
    # Replace this URL with your Gemini API endpoint
    api_url = "https://your-gemini-api-endpoint.com/generate-quiz"
    headers = {
        "Authorization": "AIzaSyBn83e1kIPM3s0j8y7eed5CxhFeHGreENE",  # Replace with your API key
        "Content-Type": "application/json",
    }

    # Make the POST request to the Gemini API
    response = requests.post(api_url, json=quiz_data, headers=headers)

    if response.status_code == 200:
        # Return the quiz data generated by Gemini API
        return response.json()
    else:
        st.error(f"Error generating quiz: {response.text}")
        return None

# URL of a Lottie animation
lottie_url = "https://lottie.host/e9cecd7f-13df-43ea-97b0-fc8c5ab43de2/DkQjWGc4DZ.json"

# Initialize session state for navigation and storing quiz data
if "page" not in st.session_state:
    st.session_state.page = "home"

# Function to navigate to another page
def navigate_to(page):
    st.session_state.page = page

# Home Page
def home_page():
    st.markdown("<h1 style='text-align: center;'>Welcome to Quiz Customizer 📚</h1>", unsafe_allow_html=True)
    st.markdown("""
    <p style='text-align: center; font-size: 18px;'>
        This tool allows you to create customized quizzes tailored to different learning needs and abilities. 
    </p>
    """, unsafe_allow_html=True)

    # Display the Lottie animation below the title
    lottie_animation = load_lottie_url(lottie_url)
    if lottie_animation:
        st_lottie(lottie_animation, speed=1, width=600, height=400, key="animation1")

    # Center-align the button
    if st.button("Start Customizing", help="Click to customize your quiz"):
        navigate_to("customize")

# Customization Page
def customize_page():
    st.markdown("<h1 style='text-align: center;'>Customize Your Quiz ✏️</h1>", unsafe_allow_html=True)
    st.markdown("""
    <p style='text-align: center; font-size: 16px;'>
        Fill in the details below to create a personalized quiz.
    </p>
    """, unsafe_allow_html=True)

    # Input fields for customization
    with st.form("quiz_form"):
        quiz_title = st.text_input("Quiz Title", placeholder="Enter the title of your quiz")
        num_questions = st.number_input("Number of Questions", min_value=1, max_value=50, step=1, value=10)
        time_limit = st.slider("Time Limit (minutes)", min_value=5, max_value=60, step=5, value=15)
        difficulty = st.selectbox("Select Difficulty", ["Easy", "Medium", "Hard"])
        special_requirements = st.text_area(
            "Special Requirements", placeholder="Mention any specific needs for this quiz."
        )

        # Accessibility features
        st.markdown("<h3>Accessibility Features</h3>", unsafe_allow_html=True)
        text_to_speech = st.checkbox("Enable Text-to-Speech", help="Read out quiz questions and options.")
        high_contrast_mode = st.checkbox("Enable High Contrast Mode", help="Use a high contrast color scheme.")
        larger_text = st.checkbox("Enable Larger Text", help="Increase font size for better readability.")

        # Submit button
        submitted = st.form_submit_button("Generate Quiz")
        if submitted:
            # Prepare data to send to Gemini API
            quiz_data = {
                "title": quiz_title,
                "num_questions": num_questions,
                "time_limit": time_limit,
                "difficulty": difficulty,
                "special_requirements": special_requirements,
                "accessibility": {
                    "text_to_speech": text_to_speech,
                    "high_contrast_mode": high_contrast_mode,
                    "larger_text": larger_text,
                },
            }
            # Call Gemini API to generate quiz
            quiz_result = generate_quiz_gemini(quiz_data)
            if quiz_result:
                # Store the generated quiz result in session state
                st.session_state.quiz = quiz_result
                navigate_to("quiz")

# Quiz Page
def quiz_page():
    st.markdown("<h1 style='text-align: center;'>Your Customized Quiz 📝</h1>", unsafe_allow_html=True)

    # Display the quiz details
    if "quiz" in st.session_state:
        quiz = st.session_state.quiz
        st.markdown(f"### Quiz Title: **{quiz['title']}**")
        st.markdown(f"**Number of Questions:** {quiz['num_questions']}")
        st.markdown(f"**Time Limit:** {quiz['time_limit']} minutes")
        st.markdown(f"**Difficulty Level:** {quiz['difficulty']}")
        st.markdown(f"**Special Requirements:** {quiz['special_requirements'] or 'None'}")
        
        # Display selected accessibility features
        st.markdown("### Accessibility Features:")
        if quiz["accessibility"]["text_to_speech"]:
            st.markdown("- **Text-to-Speech**: Enabled")
        if quiz["accessibility"]["high_contrast_mode"]:
            st.markdown("- **High Contrast Mode**: Enabled")
        if quiz["accessibility"]["larger_text"]:
            st.markdown("- **Larger Text**: Enabled")
        if not any(quiz["accessibility"].values()):
            st.markdown("No additional accessibility features selected.")

    else:
        st.warning("No quiz details found. Please go back and customize the quiz.")

    # Navigation buttons
    if st.button("Go Back"):
        navigate_to("customize")
    if st.button("Home"):
        navigate_to("home")

# Render the current page based on session state
if st.session_state.page == "home":
    home_page()
elif st.session_state.page == "customize":
    customize_page()
elif st.session_state.page == "quiz":
    quiz_page()
